version: '2'

volumes:
  softether-logs:
    driver: local

services:
  softether:
    build: .
    image: whatever4711/softether:armhf
    restart: always
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 1194:1194
    volumes:
      - /home/marcel/.container/config/vpn_server.config:/usr/local/vpnserver/vpn_server.config
      - softether-logs:/var/log/vpnserver
